version: "2"

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - "8000:8000"
    container_name: dj_container
    depends_on:
      - redis
      - db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7.2.3-alpine3.18
    container_name: redis-server
  
  celery:
    build: .
    command: celery -A project worker --loglevel=info
    depends_on:
      - redis
      - backend
  
  db:
        image: postgres:13.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: mydb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        expose:
            - 5432

volumes:
    postgres_data: {}


    
