# Generated by Django 4.2 on 2023-08-30 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_slug_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 20, 4, 27, 108980, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
    ]
