# Generated by Django 4.2 on 2023-09-29 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 18, 42, 20, 66316, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
    ]
