# Generated by Django 4.2 on 2023-09-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='company_logo')),
                ('subtitle', models.TextField(max_length=600)),
                ('facebook_link', models.URLField(blank=True, max_length=100, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=100, null=True)),
                ('youtube_link', models.URLField(blank=True, max_length=100, null=True)),
                ('phones', models.TextField(blank=True, max_length=500, null=True)),
                ('email', models.TextField(blank=True, max_length=500, null=True)),
                ('adress', models.TextField(blank=True, max_length=500, null=True)),
                ('call_us', models.TextField(blank=True, max_length=100, null=True)),
                ('eamil_us', models.TextField(blank=True, max_length=100, null=True)),
                ('android_app', models.URLField(blank=True, max_length=100, null=True)),
                ('iso_app', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
