# Generated by Django 4.2 on 2023-10-15 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_cart_orderdetail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2023, 10, 15)),
        ),
    ]
